name: Run Python Script at 9 AM EST

on:
  schedule:
    - cron: "30 18 * * *"

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Change to the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install yfinance
          pip install datetime

      - name: Execute Python Script
        run: python src/intraday-signals.py  # Replace 'your_script.py' with the name of your Python script
